# SELECT A.ID, COUNT(B.ID) CHILD_COUNT
# FROM ECOLI_DATA A LEFT JOIN ECOLI_DATA B
# ON B.PARENT_ID = A.ID
# GROUP BY 1
# ORDER BY 1;

SELECT A.ID, (SELECT COUNT(ID) FROM ECOLI_DATA B WHERE A.ID = B.PARENT_ID) CHILD_COUNT
FROM ECOLI_DATA A
ORDER BY 1;