SELECT ID, 
    CASE
        WHEN S.RANKS/CNTS <= 0.25 THEN 'CRITICAL'
        WHEN S.RANKS/CNTS <= 0.5 THEN 'HIGH'
        WHEN S.RANKS/CNTS <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM (SELECT *,
     RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) RANKS,
      COUNT(*) OVER() CNTS
     FROM ECOLI_DATA) S
ORDER BY 1;