SELECT HISTORY_ID, ROUND(DAILY_FEE * PERIOD * (1 - DISCOUNT_RATE)) FEE
FROM
(
    SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 PERIOD,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN 0
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN 0.05
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN 0.08
            ELSE 0.15
        END DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID AND CAR_TYPE = '트럭'
) SUB
ORDER BY FEE DESC, HISTORY_ID DESC;