SELECT
    CASE WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' AND GROUP_CONCAT(S.NAME) LIKE '%Python%' THEN 'A'
        WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN 'B'
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' THEN 'C'
    END GRADE, D.ID, D.EMAIL
FROM SKILLCODES S JOIN DEVELOPERS D
ON S.CODE & D.SKILL_CODE = S.CODE
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY 1, 2;